### ISSUE TITLE
Code is not in a state where contributions can be easily made

### ISSUE THREAD

**Issue by elliot-100** [Poppadomus/pygameTDS#10]
I would like to make changes, as per 'Contributions? Yes, please! Fork the repo, make your changes, and submit a pull request...' but the code is not currently in a state where this is easy to do.

I will create a PR to do these things, which I think is the bare minimum to allow any meaningful contributions by others:

- lift class definitions out of main game code and group together
- lift module function definitions out of main game code and group together

**Comment by Poppadomus** [comment]
Okay thank you for your help! I am new to github so it is helpful you are contributing to the project.
