### ISSUE TITLE
Code formatting: What maximum line length to use?

### ISSUE THREAD

**Issue by elliot-100** [Poppadomus/pygameTDS#19]
It's accepted Python dev practice to declare a maximum number of characters per line. Among other things this makes it simpler to run automatic formatting tools. 

@Poppadomus it looks like you are happy with quite long lines, are you OK with 120?

**Comment by Poppadomus** [comment]
Sometimes they just end up that way I don't think it's too important right now.

**Comment by elliot-100** [comment]
I asked this so I could set up an auto formatter.

https://trunk.io/learn/what-is-a-code-formatter-and-why-would-i-want-to-use-one
