### ISSUE TITLE
Bug: Upgrade buttons only clickable on the right half of button

### ISSUE THREAD

**Issue by FPZKryddan** [Poppadomus/pygameTDS#23]
When testing I noticed that seemingly I could only click on an upgrade button if it were done on the right half of buttons, unsure if this applied to all of them. If I click anywhere else nothing happens.

**Comment by FPZKryddan** [comment]
After further testing this only seemed to be an issue on my laptop that had 125% app scaling on in windows display settings on 1920x1080, changing this to 100% solves it. Still might be worth to note

**Comment by Poppadomus** [comment]
> When testing I noticed that seemingly I could only click on an upgrade button if it were done on the right half of buttons, unsure if this applied to all of them. If I click anywhere else nothing happens.

I fixed this issue the other then broke it again I'll have to double check.

**Comment by SageTendo** [comment]
I took a look at the implementation

From my understanding in _render_upgrade_panel_()
The positioning of the options buttons are drawn as follows:
https://github.com/Poppadomus/pygameTDS/blob/8d0eadc68ff57d008ed337c0e1b0af943f843058/Launcher.py#L807-L823

But in the event handler the collision regions are set differently:
https://github.com/Poppadomus/pygameTDS/blob/8d0eadc68ff57d008ed337c0e1b0af943f843058/Launcher.py#L1192-L1208

Could I know why this was done? In case there was a need for the differing implementations?

**Comment by SageTendo** [comment]
I refactored the code for the event handler to use that of _render_upgrade_panel()_ and it seems to work correctly. I'd like to create a PR for this if it isn't already in the works :)

Additionally, could _render_upgrade_panel()_ be used/refactored in a way that reduces repetition in the event handler?

**Comment by elliot-100** [comment]
@SageTendo I also spotted the semi-duplicated code here.

I think there's the guts 😜 of a good game here, and I wanted to put some Python/Pygame study into practice, but I found it quite difficult to understand the code and branching.

So I'm in the process of substantially refactoring my fork: https://github.com/elliot-100/pygameTDS.

I started by linting and cutting down `Launcher.py` by pulling out the simpler classes into their own modules.

It's not really set up for general contributions (maybe in the future) but would welcome a PR.

**Comment by SageTendo** [comment]
@elliot-100  I completely agree, it's quite a fun game and there's a lot of potential neat features that could be added. Plus it looked pretty nice to contribute to as my first open source project :smile: 
If you need any help with refactoring, I'd be interested in giving that a look as well.
