### ISSUE TITLE
Some globals should be refactored into `Player` class

### ISSUE THREAD

**Issue by elliot-100** [Poppadomus/pygameTDS#25]
There are quite a few module-level (so right now, global) variables and functions which should really be in the `Player` class.

Some are explicitly referred to in `global` context, which isn't usually necessary, and tends to get in the way sooner or later.

```python
# not constants, as they are assigned to:
constants['SCORE']  
constants['BLOOD']
constants['TOTAL_KILLS']

player_xp_multiplier = 1.0
player_level
player_xp
update_player_level_and_xp(xp_gained)
```
Probably `create_projectile()` as well - while in the future there could be zombies that shoot/spit/throw things, they should then have their own calls to the `Projectile` class. Right now all projectiles are shot by the player -- EDIT: didn't do this, see PR for notes.

I'm happy to raise a PR for this.

**Comment by Poppadomus** [comment]
If you could, cheers.
