### ISSUE TITLE
World wrapping bounding display problem

### ISSUE THREAD

**Issue by Poppadomus** [Poppadomus/pygameTDS#42]
In order for the world wrapping to appear fluid and work seamlessly everything needs to be positioned relative to the player after the wrap procs this ensures that sprites don't teleport from top to bottom of the camera/screen.

**Comment by elliot-100** [comment]
Can you be more specific about what effect the issue has - what entities are affected?

> everything needs to be positioned relative to the player

I think this is what the `Camera` class is supposed to do, so there may well be an issue there. Perhaps it isn't always called when it should be?

**Comment by Poppadomus** [comment]
With the new procedurally generated wrapped map when the player reaches the end of the bound for the wrapping it's like they or the entities are teleported away from each other if that makes sense, so the idea was that if all sprites are a relative distance away from the player when the wrapping occurs they wont be teleported idk if that makes sense from your POV.

**Comment by elliot-100** [comment]
This is confusing as there is no procedurally generated map in your main branch - see #43.

You'd normally develop a new feature in its own branch, and deal with problems like this there, then when you are happy with it, merge into your main branch.

**Comment by Poppadomus** [comment]
it's on the stable build updated this morning

**Comment by Poppadomus** [comment]
I'm going to revert it for now and worry about procedurally generated maps later on once there is an actual map framework.

**Comment by elliot-100** [comment]
I would suggest you close things like this as 'not planned [yet]'. Rather than 'completed'.

Then you can review what was actually completed later, e.g. when writing release notes.
