### ISSUE TITLE
What versions of Python is this intended to run on?

### ISSUE THREAD

**Issue by elliot-100** [Poppadomus/pygameTDS#6]
To put it another way, what's the lowest version it should support?

This affects the code that contributors can use.

The answer should probably be 'the highest version the repo owner has available, which supports the dependencies used'. Pygame supports Python 3.13 I think.

**Comment by Poppadomus** [comment]
I built it for 3.11

**Comment by Poppadomus** [comment]
If you are looking to distribute it for your own project, I recommend using the pyinstaller library to build (package) it.

**Comment by elliot-100** [comment]
It would be a good idea to declare the target Python version and the dependencies. The modern way of doing this is in a `pyproject.toml' file.

**Comment by Poppadomus** [comment]
I thought I declared them in the read me, but we can look into doing it the standard way if you like but now that I think about it I just remembered I rewrote the readme.

**Comment by elliot-100** [comment]
The reason to do it `pyproject.toml` or similar is so that e.g. IDEs can read it and suggest creating an virtual environment of appropriate Python version, warn if you are using code which is imcompatible with that Python version, etc.

**Comment by Poppadomus** [comment]
Good thinking I never knew about this, thank you.
